# Generated by Django 5.1.3 on 2025-05-10 21:07

import direct.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=direct.models.user_directory_path_message, verbose_name='Image'),
        ),
    ]
