# Generated by Django 5.1.3 on 2024-12-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='def.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='Title', max_length=128),
        ),
    ]
