# Generated by Django 5.1.4 on 2024-12-21 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_img_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='days',
            field=models.CharField(default='Sunday', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0), max_length=100),
        ),
    ]
