# Generated by Django 5.1.4 on 2024-12-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_user_days_user_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_time',
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
    ]
