# Generated by Django 5.1.3 on 2024-12-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_user_days_alter_user_start_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Tasks',
        ),
    ]
