# Generated by Django 5.1.3 on 2024-12-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='N/A', max_length=128),
        ),
    ]
