# Generated by Django 5.1.3 on 2025-01-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_tasks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(default='Create Task', max_length=255),
        ),
    ]
