# Generated by Django 5.1.3 on 2025-01-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_tasks_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='img',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(blank=True, default='N/A', max_length=128, null=True),
        ),
    ]
