# Generated by Django 5.1.4 on 2024-12-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_friend_created_at_profilesuggestion_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profilesuggestion',
            name='suggestion_for',
        ),
        migrations.RemoveField(
            model_name='profilesuggestion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ProfileSuggestion',
        ),
    ]
